### ISSUE TITLE
「傀異練成設定」で防具を指定せずに、防具のレア度(抽選テーブル)と練成結果のみを入力してスキルシミュを行いたい

### ISSUE THREAD

**Issue by sasa0323** [EXXXI/RiseSim#104]
傀異練成結果をどの防具に練成結果を移植するかを検討するとき
「傀異練成設定」で防具を指定せずに、防具のレア度(抽選テーブル)と練成結果のみを入力してスキルのシミュレータを行いたい

(補足・参考URL)
・練成結果の移植について
https://kuroyonhon.com/mhrisesb/memo/54.php#7

・傀異練成の抽選テーブルについて
https://hyperwiki.jp/mhr/custom-buildup/

・マイナススキルについて
マイナススキルの抽選時、1-12の乱数を発生させ、マイナスするスキルを抽選する仕様を思われるため
マイナススキルは１～１２の番号で指定する形が良い？

(例) 1-12の内、3番目のスキルが抽選された場合
　　▼
①②③④⑤⑥⑦⑧⑨⑩⑪⑫　→１～１２の乱数で３が抽選
①②①②①②①②①②①②　→2スキル防具の場合、1番目のスキルがマイナスされる
①②③①②③①②③①②③　→3スキル防具の場合、3番目のスキルがマイナスされる
①②③④①②③④①②③④　→4スキル防具の場合、3番目のスキルがマイナスされる

**Comment by EXXXI** [comment]
クローズしておきます
