### ISSUE TITLE
特定の検索がヒットしません

### ISSUE THREAD

**Issue by jbskw** [EXXXI/RiseSim#107]
いつも便利に利用させていただいております。

RiseSimではヒットしないけど組める装備を発見したと思います。
通常検索ではヒットしませんが、理想錬成検索をするとカイザー頭にc6s1を錬成しろと出ます。
しかし既に弱特s1のカイザー頭を持っているので、錬成しなくても装備を組めます。

またお守りと傀異錬成設定は(泣)から全てインポートしています。
スキルシミュ(泣)では同じスキルでヒットし、その通り組めます。

RiseSimと泣シミュの画面とsaveフォルダ、logフォルダを添付します。
ご確認いただければ幸いです。

[kaiser.zip](https://github.com/EXXXI/RiseSim/files/10820893/kaiser.zip)

**Comment by EXXXI** [comment]
報告ありがとうございます&バグってて申し訳ないです。
煽衛の装飾品のデータが4スロ扱いになっていました。
先ほど修正して更新しました。

**Comment by jbskw** [comment]
さっそく対応いただきありがとうございました。（添付ファイルは削除させていただきました）
