### ISSUE TITLE
スロットが間違っている

### ISSUE THREAD

**Issue by b100cyukist** [EXXXI/RiseSim#54]
例：ゴールドルナシリーズのスロットがおかしい
正しくは
頭2-2
胴3-2
腕4-2-1
腰3-2
脚4-2
です。取り急ぎ

**Comment by b100cyukist** [comment]
プライドシリーズもおかしいです。
正しくは
頭3-2
胴3
腕3-1
腰2-1-1
脚2-2
です。

**Comment by b100cyukist** [comment]
対応確認しました。ありがとうございました。

**Comment by b100cyukist** [comment]
腕：ゴールドルナアーム,4-2-0
正しくは4-2-1です。

**Comment by EXXXI** [comment]
ありがとうございます。修正しました。
